---
kind: pipeline
name: default

steps:
- name: build
  image: rancher/dapper:v0.5.2
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: build-all-binaries
  image: golang:1.13.12
  environment:
    CROSS: 1
    VERSION: ${DRONE_TAG}
  commands:
  - apt-get update
  - apt-get install -y xz-utils zip rsync jq curl ca-certificates
  - mkdir -p /go/src/github.com/rawmind0
  - ln -s /drone/src /go/src/github.com/rawmind0/ssh-client
  - cd /go/src/github.com/rawmind0/ssh-client
  - make build
  - make package
  when:
    event: tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - dist/artifacts/${DRONE_TAG}/ssh-client_*
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      include: [ refs/tags/*rc* ]

- name: github_binary_release
  image: plugins/github-release
  settings:
    files:
    - dist/artifacts/${DRONE_TAG}/ssh-client_*
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]

volumes:
- name: socket
  host:
    path: /var/run/docker.sock